import streamlit as st
import google.generativeai as genai
import tempfile
import os

GEMINI_API_KEY = st.sidebar.text_input("Gemini API Key", type="password")

if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)
    MODEL_NAME = "gemini-2.5-flash"
else:
    st.warning("Provide your Gemini API Key to continue.")
    st.stop()

# Initialize file management tracking session state
if "uploaded_gemini_files" not in st.session_state:
    st.session_state.uploaded_gemini_files = []

st.title("📂 Gemini Native File Search Engine")

# Multi-modal support files upload
uploaded_files = st.file_uploader(
    "Upload Documents for Direct File Search (PDFs, Images, Text, Audio, Video)", 
    type=["pdf", "txt", "png", "jpg", "jpeg", "mp3", "wav", "mp4"], 
    accept_multiple_files=True
)

if st.button("Process & Upload to File API"):
    if uploaded_files:
        for file in uploaded_files:
            # Temporary file configuration to bypass memory pipes
            with tempfile.NamedTemporaryFile(delete=False, suffix=f"_{file.name}") as temp_file:
                temp_file.write(file.read())
                temp_path = temp_file.name
            
            with st.spinner(f"Uploading {file.name} to Gemini Cloud Space..."):
                # native ingestion to Google File manager API
                gemini_file = genai.upload_file(path=temp_path)
                st.session_state.uploaded_gemini_files.append(gemini_file)
            
            os.remove(temp_path)
        st.success(f"Successfully staged {len(uploaded_files)} objects!")

if st.session_state.uploaded_gemini_files:
    st.write("### Currently Indexed Files:")
    for f in st.session_state.uploaded_gemini_files:
        st.caption(f"- `{f.display_name}` (Status: {f.state})")

st.divider()

user_query = st.text_input("Submit query across document context:")

if user_query:
    system_prompt = (
        "You are parsing through documents submitted natively via the File API structure. "
        "Carefully analyze all associated attachments. If the answer to the user's question cannot "
        "be found in the attached documents, respond with: 'Nothing found relevant' "
        "and then provide a fallback response derived from your own knowledge. "
        "If the answer is found in the documents, append '(This response is generated by gemini ai)' at the very end."
    )
    
    model = genai.GenerativeModel(model_name=MODEL_NAME, system_instruction=system_prompt)
    
    # Construct multi-modal payload: files list + text string
    payload = []
    payload.extend(st.session_state.uploaded_gemini_files)
    payload.append(user_query)
    
    with st.spinner("Analyzing data vectors..."):
        response = model.generate_content(payload)
        
    st.write("### Engine Response:")
    st.write(response.text)

# Cleanup configuration option
if st.sidebar.button("Flush Files Cache"):
    for f in st.session_state.uploaded_gemini_files:
        genai.delete_file(f.name)
    st.session_state.uploaded_gemini_files = []
    st.sidebar.success("Cloud directory purged.")
