import streamlit as st
from google import genai
import tempfile
import os
import re

# --- 1. SANITIZED API KEY AUTHENTICATION BLOCK ---
if "GEMINI_API_KEY" in st.secrets:
    raw_key = st.secrets["GEMINI_API_KEY"]
else:
    raw_key = st.sidebar.text_input("Gemini API Key", type="password")

if raw_key:
    # Strict cleaning to scrub out any accidental smart/curly quotes causing the error
    GEMINI_API_KEY = str(raw_key).strip().replace("’", "").replace("‘", "").replace('"', '').replace("'", "")
    
    try:
        GEMINI_API_KEY.encode('ascii')
    except UnicodeEncodeError:
        st.error("Your API key still contains hidden non-ASCII characters. Please clear the text box and paste it again.")
        st.stop()

    # Initialize the modern unified client built for new AQ keys
    client = genai.Client(api_key=GEMINI_API_KEY)
    MODEL_NAME = "gemini-3.6-flash"
else:
    st.warning("Provide your Gemini API Key to continue.")
    st.stop()

# Initialize file management tracking session state
if "uploaded_gemini_files" not in st.session_state:
    st.session_state.uploaded_gemini_files = []

st.title("📂 Gemini Native File Search Engine")

# Multi-modal support files upload
uploaded_files = st.file_uploader(
    "Upload Documents for Direct File Search (PDFs, Images, Text, Audio, Video)", 
    type=["pdf", "txt", "png", "jpg", "jpeg", "mp3", "wav", "mp4"], 
    accept_multiple_files=True
)

if st.button("Process & Upload to File API"):
    if uploaded_files:
        for file in uploaded_files:
            # FIX: Clean the file name to remove ANY non-ASCII or special characters before processing
            clean_name = re.sub(r'[^\x00-\x7F]+', '', file.name)
            # Remove spaces just to be absolutely safe with header boundaries
            clean_name = clean_name.replace(" ", "_")
            
            # If the filename becomes completely empty after stripping, provide a default fallback name
            if not clean_name or clean_name.startswith('.'):
                clean_name = f"uploaded_media_{int(tempfile.time.time())}"
            
            # Get the file extension
            _, ext = os.path.splitext(file.name)
            
            with tempfile.NamedTemporaryFile(delete=False, suffix=f"_{clean_name}{ext}") as temp_file:
                temp_file.write(file.read())
                temp_path = temp_file.name
            
            with st.spinner(f"Uploading {file.name} to Gemini Cloud Space..."):
                try:
                    # Pass the fully sanitized temporary file path safely
                    gemini_file = client.files.upload(file=temp_path)
                    st.session_state.uploaded_gemini_files.append(gemini_file)
                except Exception as upload_error:
                    st.error(f"Failed to upload {file.name}: {str(upload_error)}")
                finally:
                    # Ensure the local OS file boundary is cleaned up even if the network fails
                    if os.path.exists(temp_path):
                        os.remove(temp_path)
                        
        st.success(f"Successfully processed objects!")

if st.session_state.uploaded_gemini_files:
    st.write("### Currently Indexed Files:")
    for f in st.session_state.uploaded_gemini_files:
        st.caption(f"- `{f.display_name}`")

st.divider()

user_query = st.text_input("Submit query across document context:")

if user_query:
    system_prompt = (
        "You are parsing through documents submitted natively via the File API structure. "
        "Carefully analyze all associated attachments. If the answer to the user's question cannot "
        "be found in the attached documents, respond with: 'Nothing found relevant' "
        "and then provide a fallback response derived from your own knowledge. "
        "If the answer is found in the documents, append '(This response is generated by gemini ai)' at the very end."
    )
    
    contents = []
    contents.extend(st.session_state.uploaded_gemini_files)
    contents.append(user_query)
    
    with st.spinner("Analyzing data vectors..."):
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=contents,
            config={"system_instruction": system_prompt}
        )
        
    st.write("### Engine Response:")
    st.write(response.text)

if st.sidebar.button("Flush Files Cache"):
    for f in st.session_state.uploaded_gemini_files:
        try:
            client.files.delete(name=f.name)
        except Exception:
            pass
    st.session_state.uploaded_gemini_files = []
    st.sidebar.success("Cloud directory purged.")
